### ISSUE TITLE
plash-import-lxc needs future-proofing (strange version names)

### ISSUE THREAD

**Issue by E100Beta** [ihucos/plash#113]
There are combinations of distro and version name on https://images.linuxcontainers.org that plash does not handle very well.
Examples:
devuan-ascii
alt-Sisyphus
alt-p9

Currently plash fails while trying to download anything from lxc.
Why not ignore these distros altogether, along with anything that's not the image requested?
At least it protects from use-case where these things make plash fail even if user needed completely different image.

**Comment by ihucos** [comment]
Thank you very much for the issue

> Currently plash fails while trying to download anything from lxc.

That is obviously not good. I will make it more stable. Not trying to interpret every distro and version is definitely a good idea.

**Comment by ihucos** [comment]
Fix is in master: https://github.com/ihucos/plash/pull/114
I'd appreciate any input. Feel free to close this issue if this solves the problem.

**Comment by E100Beta** [comment]
Seems to work, the list of all images available on lxc seems like a very convenient feature, thank you!
